[build]
  command = "cd functions && npm install"
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
